// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class PlayerRoleDTODef {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_PlayerRoleDTOPB__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::PlayerRoleDTOPB, global::PlayerRoleDTOPB.Builder> internal__static_PlayerRoleDTOPB__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static PlayerRoleDTODef() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZQbGF5ZXJSb2xlRFRPRGVmLnByb3RvIicKD1BsYXllclJvbGVEVE9QQhIU", 
          "CgxwbGF5ZXJSb2xlSWQYASACKANCHQobb3JnLmdhbWVwcm90b3R5cGUucHJv", 
        "dG8uc3Jj"));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_PlayerRoleDTOPB__Descriptor = Descriptor.MessageTypes[0];
      internal__static_PlayerRoleDTOPB__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::PlayerRoleDTOPB, global::PlayerRoleDTOPB.Builder>(internal__static_PlayerRoleDTOPB__Descriptor,
              new string[] { "PlayerRoleId", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class PlayerRoleDTOPB : pb::GeneratedMessage<PlayerRoleDTOPB, PlayerRoleDTOPB.Builder> {
  private PlayerRoleDTOPB() { }
  private static readonly PlayerRoleDTOPB defaultInstance = new PlayerRoleDTOPB().MakeReadOnly();
  private static readonly string[] _playerRoleDTOPBFieldNames = new string[] { "playerRoleId" };
  private static readonly uint[] _playerRoleDTOPBFieldTags = new uint[] { 8 };
  public static PlayerRoleDTOPB DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override PlayerRoleDTOPB DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override PlayerRoleDTOPB ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::PlayerRoleDTODef.internal__static_PlayerRoleDTOPB__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<PlayerRoleDTOPB, PlayerRoleDTOPB.Builder> InternalFieldAccessors {
    get { return global::PlayerRoleDTODef.internal__static_PlayerRoleDTOPB__FieldAccessorTable; }
  }
  
  public const int PlayerRoleIdFieldNumber = 1;
  private bool hasPlayerRoleId;
  private long playerRoleId_;
  public bool HasPlayerRoleId {
    get { return hasPlayerRoleId; }
  }
  public long PlayerRoleId {
    get { return playerRoleId_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasPlayerRoleId) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _playerRoleDTOPBFieldNames;
    if (hasPlayerRoleId) {
      output.WriteInt64(1, field_names[0], PlayerRoleId);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasPlayerRoleId) {
      size += pb::CodedOutputStream.ComputeInt64Size(1, PlayerRoleId);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static PlayerRoleDTOPB ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static PlayerRoleDTOPB ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private PlayerRoleDTOPB MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(PlayerRoleDTOPB prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<PlayerRoleDTOPB, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(PlayerRoleDTOPB cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private PlayerRoleDTOPB result;
    
    private PlayerRoleDTOPB PrepareBuilder() {
      if (resultIsReadOnly) {
        PlayerRoleDTOPB original = result;
        result = new PlayerRoleDTOPB();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override PlayerRoleDTOPB MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::PlayerRoleDTOPB.Descriptor; }
    }
    
    public override PlayerRoleDTOPB DefaultInstanceForType {
      get { return global::PlayerRoleDTOPB.DefaultInstance; }
    }
    
    public override PlayerRoleDTOPB BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is PlayerRoleDTOPB) {
        return MergeFrom((PlayerRoleDTOPB) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(PlayerRoleDTOPB other) {
      if (other == global::PlayerRoleDTOPB.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasPlayerRoleId) {
        PlayerRoleId = other.PlayerRoleId;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_playerRoleDTOPBFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _playerRoleDTOPBFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            result.hasPlayerRoleId = input.ReadInt64(ref result.playerRoleId_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasPlayerRoleId {
      get { return result.hasPlayerRoleId; }
    }
    public long PlayerRoleId {
      get { return result.PlayerRoleId; }
      set { SetPlayerRoleId(value); }
    }
    public Builder SetPlayerRoleId(long value) {
      PrepareBuilder();
      result.hasPlayerRoleId = true;
      result.playerRoleId_ = value;
      return this;
    }
    public Builder ClearPlayerRoleId() {
      PrepareBuilder();
      result.hasPlayerRoleId = false;
      result.playerRoleId_ = 0L;
      return this;
    }
  }
  static PlayerRoleDTOPB() {
    object.ReferenceEquals(global::PlayerRoleDTODef.Descriptor, null);
  }
}

#endregion


#endregion Designer generated code
