// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class PlayerEquipDTODef {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_PlayerEquipDTOPB__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::PlayerEquipDTOPB, global::PlayerEquipDTOPB.Builder> internal__static_PlayerEquipDTOPB__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static PlayerEquipDTODef() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdQbGF5ZXJFcXVpcERUT0RlZi5wcm90byJgChBQbGF5ZXJFcXVpcERUT1BC", 
          "EhUKDXBsYXllckVxdWlwSWQYASACKAMSFAoMcGxheWVyUm9sZUlkGAIgAigD", 
          "Eg8KB2VxdWlwSWQYAyACKAMSDgoGc3RhdHVzGAQgASgDQh0KG29yZy5nYW1l", 
        "cHJvdG90eXBlLnByb3RvLnNyYw=="));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_PlayerEquipDTOPB__Descriptor = Descriptor.MessageTypes[0];
      internal__static_PlayerEquipDTOPB__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::PlayerEquipDTOPB, global::PlayerEquipDTOPB.Builder>(internal__static_PlayerEquipDTOPB__Descriptor,
              new string[] { "PlayerEquipId", "PlayerRoleId", "EquipId", "Status", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class PlayerEquipDTOPB : pb::GeneratedMessage<PlayerEquipDTOPB, PlayerEquipDTOPB.Builder> {
  private PlayerEquipDTOPB() { }
  private static readonly PlayerEquipDTOPB defaultInstance = new PlayerEquipDTOPB().MakeReadOnly();
  private static readonly string[] _playerEquipDTOPBFieldNames = new string[] { "equipId", "playerEquipId", "playerRoleId", "status" };
  private static readonly uint[] _playerEquipDTOPBFieldTags = new uint[] { 24, 8, 16, 32 };
  public static PlayerEquipDTOPB DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override PlayerEquipDTOPB DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override PlayerEquipDTOPB ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::PlayerEquipDTODef.internal__static_PlayerEquipDTOPB__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<PlayerEquipDTOPB, PlayerEquipDTOPB.Builder> InternalFieldAccessors {
    get { return global::PlayerEquipDTODef.internal__static_PlayerEquipDTOPB__FieldAccessorTable; }
  }
  
  public const int PlayerEquipIdFieldNumber = 1;
  private bool hasPlayerEquipId;
  private long playerEquipId_;
  public bool HasPlayerEquipId {
    get { return hasPlayerEquipId; }
  }
  public long PlayerEquipId {
    get { return playerEquipId_; }
  }
  
  public const int PlayerRoleIdFieldNumber = 2;
  private bool hasPlayerRoleId;
  private long playerRoleId_;
  public bool HasPlayerRoleId {
    get { return hasPlayerRoleId; }
  }
  public long PlayerRoleId {
    get { return playerRoleId_; }
  }
  
  public const int EquipIdFieldNumber = 3;
  private bool hasEquipId;
  private long equipId_;
  public bool HasEquipId {
    get { return hasEquipId; }
  }
  public long EquipId {
    get { return equipId_; }
  }
  
  public const int StatusFieldNumber = 4;
  private bool hasStatus;
  private long status_;
  public bool HasStatus {
    get { return hasStatus; }
  }
  public long Status {
    get { return status_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasPlayerEquipId) return false;
      if (!hasPlayerRoleId) return false;
      if (!hasEquipId) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _playerEquipDTOPBFieldNames;
    if (hasPlayerEquipId) {
      output.WriteInt64(1, field_names[1], PlayerEquipId);
    }
    if (hasPlayerRoleId) {
      output.WriteInt64(2, field_names[2], PlayerRoleId);
    }
    if (hasEquipId) {
      output.WriteInt64(3, field_names[0], EquipId);
    }
    if (hasStatus) {
      output.WriteInt64(4, field_names[3], Status);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasPlayerEquipId) {
      size += pb::CodedOutputStream.ComputeInt64Size(1, PlayerEquipId);
    }
    if (hasPlayerRoleId) {
      size += pb::CodedOutputStream.ComputeInt64Size(2, PlayerRoleId);
    }
    if (hasEquipId) {
      size += pb::CodedOutputStream.ComputeInt64Size(3, EquipId);
    }
    if (hasStatus) {
      size += pb::CodedOutputStream.ComputeInt64Size(4, Status);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static PlayerEquipDTOPB ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static PlayerEquipDTOPB ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private PlayerEquipDTOPB MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(PlayerEquipDTOPB prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<PlayerEquipDTOPB, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(PlayerEquipDTOPB cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private PlayerEquipDTOPB result;
    
    private PlayerEquipDTOPB PrepareBuilder() {
      if (resultIsReadOnly) {
        PlayerEquipDTOPB original = result;
        result = new PlayerEquipDTOPB();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override PlayerEquipDTOPB MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::PlayerEquipDTOPB.Descriptor; }
    }
    
    public override PlayerEquipDTOPB DefaultInstanceForType {
      get { return global::PlayerEquipDTOPB.DefaultInstance; }
    }
    
    public override PlayerEquipDTOPB BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is PlayerEquipDTOPB) {
        return MergeFrom((PlayerEquipDTOPB) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(PlayerEquipDTOPB other) {
      if (other == global::PlayerEquipDTOPB.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasPlayerEquipId) {
        PlayerEquipId = other.PlayerEquipId;
      }
      if (other.HasPlayerRoleId) {
        PlayerRoleId = other.PlayerRoleId;
      }
      if (other.HasEquipId) {
        EquipId = other.EquipId;
      }
      if (other.HasStatus) {
        Status = other.Status;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_playerEquipDTOPBFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _playerEquipDTOPBFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            result.hasPlayerEquipId = input.ReadInt64(ref result.playerEquipId_);
            break;
          }
          case 16: {
            result.hasPlayerRoleId = input.ReadInt64(ref result.playerRoleId_);
            break;
          }
          case 24: {
            result.hasEquipId = input.ReadInt64(ref result.equipId_);
            break;
          }
          case 32: {
            result.hasStatus = input.ReadInt64(ref result.status_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasPlayerEquipId {
      get { return result.hasPlayerEquipId; }
    }
    public long PlayerEquipId {
      get { return result.PlayerEquipId; }
      set { SetPlayerEquipId(value); }
    }
    public Builder SetPlayerEquipId(long value) {
      PrepareBuilder();
      result.hasPlayerEquipId = true;
      result.playerEquipId_ = value;
      return this;
    }
    public Builder ClearPlayerEquipId() {
      PrepareBuilder();
      result.hasPlayerEquipId = false;
      result.playerEquipId_ = 0L;
      return this;
    }
    
    public bool HasPlayerRoleId {
      get { return result.hasPlayerRoleId; }
    }
    public long PlayerRoleId {
      get { return result.PlayerRoleId; }
      set { SetPlayerRoleId(value); }
    }
    public Builder SetPlayerRoleId(long value) {
      PrepareBuilder();
      result.hasPlayerRoleId = true;
      result.playerRoleId_ = value;
      return this;
    }
    public Builder ClearPlayerRoleId() {
      PrepareBuilder();
      result.hasPlayerRoleId = false;
      result.playerRoleId_ = 0L;
      return this;
    }
    
    public bool HasEquipId {
      get { return result.hasEquipId; }
    }
    public long EquipId {
      get { return result.EquipId; }
      set { SetEquipId(value); }
    }
    public Builder SetEquipId(long value) {
      PrepareBuilder();
      result.hasEquipId = true;
      result.equipId_ = value;
      return this;
    }
    public Builder ClearEquipId() {
      PrepareBuilder();
      result.hasEquipId = false;
      result.equipId_ = 0L;
      return this;
    }
    
    public bool HasStatus {
      get { return result.hasStatus; }
    }
    public long Status {
      get { return result.Status; }
      set { SetStatus(value); }
    }
    public Builder SetStatus(long value) {
      PrepareBuilder();
      result.hasStatus = true;
      result.status_ = value;
      return this;
    }
    public Builder ClearStatus() {
      PrepareBuilder();
      result.hasStatus = false;
      result.status_ = 0L;
      return this;
    }
  }
  static PlayerEquipDTOPB() {
    object.ReferenceEquals(global::PlayerEquipDTODef.Descriptor, null);
  }
}

#endregion


#endregion Designer generated code
