// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CharacterDTODef.proto

package org.gameprototype.proto.src;

public final class CharacterDTODef {
  private CharacterDTODef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CharacterDTOPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CharacterDTOPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 accountId = 1;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required int64 accountId = 1;</code>
     */
    long getAccountId();

    /**
     * <code>required int64 playerId = 2;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int64 playerId = 2;</code>
     */
    long getPlayerId();

    /**
     * <code>required int64 sresId = 3;</code>
     */
    boolean hasSresId();
    /**
     * <code>required int64 sresId = 3;</code>
     */
    long getSresId();

    /**
     * <code>required int64 mapId = 4;</code>
     */
    boolean hasMapId();
    /**
     * <code>required int64 mapId = 4;</code>
     */
    long getMapId();

    /**
     * <code>required int64 termId = 5;</code>
     */
    boolean hasTermId();
    /**
     * <code>required int64 termId = 5;</code>
     */
    long getTermId();
  }
  /**
   * Protobuf type {@code CharacterDTOPB}
   */
  public static final class CharacterDTOPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CharacterDTOPB)
      CharacterDTOPBOrBuilder {
    // Use CharacterDTOPB.newBuilder() to construct.
    private CharacterDTOPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CharacterDTOPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CharacterDTOPB defaultInstance;
    public static CharacterDTOPB getDefaultInstance() {
      return defaultInstance;
    }

    public CharacterDTOPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CharacterDTOPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sresId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              mapId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              termId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.CharacterDTODef.internal_static_CharacterDTOPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.CharacterDTODef.internal_static_CharacterDTOPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.class, org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.Builder.class);
    }

    public static com.google.protobuf.Parser<CharacterDTOPB> PARSER =
        new com.google.protobuf.AbstractParser<CharacterDTOPB>() {
      public CharacterDTOPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CharacterDTOPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CharacterDTOPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>required int64 accountId = 1;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 accountId = 1;</code>
     */
    public long getAccountId() {
      return accountId_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>required int64 playerId = 2;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 playerId = 2;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int SRESID_FIELD_NUMBER = 3;
    private long sresId_;
    /**
     * <code>required int64 sresId = 3;</code>
     */
    public boolean hasSresId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 sresId = 3;</code>
     */
    public long getSresId() {
      return sresId_;
    }

    public static final int MAPID_FIELD_NUMBER = 4;
    private long mapId_;
    /**
     * <code>required int64 mapId = 4;</code>
     */
    public boolean hasMapId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 mapId = 4;</code>
     */
    public long getMapId() {
      return mapId_;
    }

    public static final int TERMID_FIELD_NUMBER = 5;
    private long termId_;
    /**
     * <code>required int64 termId = 5;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 termId = 5;</code>
     */
    public long getTermId() {
      return termId_;
    }

    private void initFields() {
      accountId_ = 0L;
      playerId_ = 0L;
      sresId_ = 0L;
      mapId_ = 0L;
      termId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSresId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMapId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTermId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sresId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, mapId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, termId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sresId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, mapId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, termId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CharacterDTOPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CharacterDTOPB)
        org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.CharacterDTODef.internal_static_CharacterDTOPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.CharacterDTODef.internal_static_CharacterDTOPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.class, org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sresId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        mapId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        termId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.CharacterDTODef.internal_static_CharacterDTOPB_descriptor;
      }

      public org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB getDefaultInstanceForType() {
        return org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.getDefaultInstance();
      }

      public org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB build() {
        org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB buildPartial() {
        org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB result = new org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sresId_ = sresId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mapId_ = mapId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.termId_ = termId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB) {
          return mergeFrom((org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB other) {
        if (other == org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasSresId()) {
          setSresId(other.getSresId());
        }
        if (other.hasMapId()) {
          setMapId(other.getMapId());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasSresId()) {
          
          return false;
        }
        if (!hasMapId()) {
          
          return false;
        }
        if (!hasTermId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.CharacterDTODef.CharacterDTOPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long accountId_ ;
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>required int64 playerId = 2;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 playerId = 2;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int64 playerId = 2;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private long sresId_ ;
      /**
       * <code>required int64 sresId = 3;</code>
       */
      public boolean hasSresId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 sresId = 3;</code>
       */
      public long getSresId() {
        return sresId_;
      }
      /**
       * <code>required int64 sresId = 3;</code>
       */
      public Builder setSresId(long value) {
        bitField0_ |= 0x00000004;
        sresId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sresId = 3;</code>
       */
      public Builder clearSresId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sresId_ = 0L;
        onChanged();
        return this;
      }

      private long mapId_ ;
      /**
       * <code>required int64 mapId = 4;</code>
       */
      public boolean hasMapId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 mapId = 4;</code>
       */
      public long getMapId() {
        return mapId_;
      }
      /**
       * <code>required int64 mapId = 4;</code>
       */
      public Builder setMapId(long value) {
        bitField0_ |= 0x00000008;
        mapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 mapId = 4;</code>
       */
      public Builder clearMapId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mapId_ = 0L;
        onChanged();
        return this;
      }

      private long termId_ ;
      /**
       * <code>required int64 termId = 5;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 termId = 5;</code>
       */
      public long getTermId() {
        return termId_;
      }
      /**
       * <code>required int64 termId = 5;</code>
       */
      public Builder setTermId(long value) {
        bitField0_ |= 0x00000010;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 termId = 5;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        termId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CharacterDTOPB)
    }

    static {
      defaultInstance = new CharacterDTOPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CharacterDTOPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CharacterDTOPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CharacterDTOPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CharacterDTODef.proto\"d\n\016CharacterDTOP" +
      "B\022\021\n\taccountId\030\001 \002(\003\022\020\n\010playerId\030\002 \002(\003\022\016" +
      "\n\006sresId\030\003 \002(\003\022\r\n\005mapId\030\004 \002(\003\022\016\n\006termId\030" +
      "\005 \002(\003B\035\n\033org.gameprototype.proto.src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CharacterDTOPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CharacterDTOPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CharacterDTOPB_descriptor,
        new java.lang.String[] { "AccountId", "PlayerId", "SresId", "MapId", "TermId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
