// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonRespDef.proto

package org.gameprototype.proto.src;

public final class CommonRespDef {
  private CommonRespDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommonResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .CommonResp.RespCode code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required .CommonResp.RespCode code = 1;</code>
     */
    org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode getCode();

    /**
     * <code>optional string info = 2;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 2;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 2;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code CommonResp}
   */
  public static final class CommonResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CommonResp)
      CommonRespOrBuilder {
    // Use CommonResp.newBuilder() to construct.
    private CommonResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommonResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommonResp defaultInstance;
    public static CommonResp getDefaultInstance() {
      return defaultInstance;
    }

    public CommonResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommonResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode value = org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              info_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.CommonRespDef.internal_static_CommonResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.CommonRespDef.internal_static_CommonResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.CommonRespDef.CommonResp.class, org.gameprototype.proto.src.CommonRespDef.CommonResp.Builder.class);
    }

    public static com.google.protobuf.Parser<CommonResp> PARSER =
        new com.google.protobuf.AbstractParser<CommonResp>() {
      public CommonResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommonResp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code CommonResp.RespCode}
     */
    public enum RespCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       *
       * <pre>
       * 成功
       * </pre>
       */
      SUCCESS(0, 0),
      /**
       * <code>PARSE_REQ_PARAM_ERROR = 400;</code>
       *
       * <pre>
       *解析参数错误
       * </pre>
       */
      PARSE_REQ_PARAM_ERROR(1, 400),
      /**
       * <code>INTERNAL_ERROR = 500;</code>
       *
       * <pre>
       *请求执行失败
       * </pre>
       */
      INTERNAL_ERROR(2, 500),
      /**
       * <code>LOGIN_ACCOUNT_UNEXIST = -1;</code>
       *
       * <pre>
       *登录帐号不存在
       * </pre>
       */
      LOGIN_ACCOUNT_UNEXIST(3, -1),
      /**
       * <code>LOGIN_PASSWORD_ERROR = -2;</code>
       *
       * <pre>
       *密码错误，登录失败
       * </pre>
       */
      LOGIN_PASSWORD_ERROR(4, -2),
      /**
       * <code>LOGIN_ACCOUNT_ALREADY_ONLINE = -3;</code>
       *
       * <pre>
       *帐号已登录，登录失败
       * </pre>
       */
      LOGIN_ACCOUNT_ALREADY_ONLINE(5, -3),
      /**
       * <code>REGISTER_ACCOUNT_ALREADY_EXISTS = -4;</code>
       *
       * <pre>
       *帐号已存在,注册失败
       * </pre>
       */
      REGISTER_ACCOUNT_ALREADY_EXISTS(6, -4),
      /**
       * <code>REGISTER_ACCOUNT_NAME_ILLEGAL = -5;</code>
       *
       * <pre>
       *帐号不合法，注册失败
       * </pre>
       */
      REGISTER_ACCOUNT_NAME_ILLEGAL(7, -5),
      /**
       * <code>REGISTER_ACCOUNT_PASSWORD_ILLEGAL = -6;</code>
       *
       * <pre>
       *密码不合法，注册失败
       * </pre>
       */
      REGISTER_ACCOUNT_PASSWORD_ILLEGAL(8, -6),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       *
       * <pre>
       * 成功
       * </pre>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>PARSE_REQ_PARAM_ERROR = 400;</code>
       *
       * <pre>
       *解析参数错误
       * </pre>
       */
      public static final int PARSE_REQ_PARAM_ERROR_VALUE = 400;
      /**
       * <code>INTERNAL_ERROR = 500;</code>
       *
       * <pre>
       *请求执行失败
       * </pre>
       */
      public static final int INTERNAL_ERROR_VALUE = 500;
      /**
       * <code>LOGIN_ACCOUNT_UNEXIST = -1;</code>
       *
       * <pre>
       *登录帐号不存在
       * </pre>
       */
      public static final int LOGIN_ACCOUNT_UNEXIST_VALUE = -1;
      /**
       * <code>LOGIN_PASSWORD_ERROR = -2;</code>
       *
       * <pre>
       *密码错误，登录失败
       * </pre>
       */
      public static final int LOGIN_PASSWORD_ERROR_VALUE = -2;
      /**
       * <code>LOGIN_ACCOUNT_ALREADY_ONLINE = -3;</code>
       *
       * <pre>
       *帐号已登录，登录失败
       * </pre>
       */
      public static final int LOGIN_ACCOUNT_ALREADY_ONLINE_VALUE = -3;
      /**
       * <code>REGISTER_ACCOUNT_ALREADY_EXISTS = -4;</code>
       *
       * <pre>
       *帐号已存在,注册失败
       * </pre>
       */
      public static final int REGISTER_ACCOUNT_ALREADY_EXISTS_VALUE = -4;
      /**
       * <code>REGISTER_ACCOUNT_NAME_ILLEGAL = -5;</code>
       *
       * <pre>
       *帐号不合法，注册失败
       * </pre>
       */
      public static final int REGISTER_ACCOUNT_NAME_ILLEGAL_VALUE = -5;
      /**
       * <code>REGISTER_ACCOUNT_PASSWORD_ILLEGAL = -6;</code>
       *
       * <pre>
       *密码不合法，注册失败
       * </pre>
       */
      public static final int REGISTER_ACCOUNT_PASSWORD_ILLEGAL_VALUE = -6;


      public final int getNumber() { return value; }

      public static RespCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 400: return PARSE_REQ_PARAM_ERROR;
          case 500: return INTERNAL_ERROR;
          case -1: return LOGIN_ACCOUNT_UNEXIST;
          case -2: return LOGIN_PASSWORD_ERROR;
          case -3: return LOGIN_ACCOUNT_ALREADY_ONLINE;
          case -4: return REGISTER_ACCOUNT_ALREADY_EXISTS;
          case -5: return REGISTER_ACCOUNT_NAME_ILLEGAL;
          case -6: return REGISTER_ACCOUNT_PASSWORD_ILLEGAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RespCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RespCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RespCode>() {
              public RespCode findValueByNumber(int number) {
                return RespCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.gameprototype.proto.src.CommonRespDef.CommonResp.getDescriptor().getEnumTypes().get(0);
      }

      private static final RespCode[] VALUES = values();

      public static RespCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RespCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CommonResp.RespCode)
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode code_;
    /**
     * <code>required .CommonResp.RespCode code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CommonResp.RespCode code = 1;</code>
     */
    public org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode getCode() {
      return code_;
    }

    public static final int INFO_FIELD_NUMBER = 2;
    private java.lang.Object info_;
    /**
     * <code>optional string info = 2;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string info = 2;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode.SUCCESS;
      info_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.CommonRespDef.CommonResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.CommonRespDef.CommonResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommonResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommonResp)
        org.gameprototype.proto.src.CommonRespDef.CommonRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.CommonRespDef.internal_static_CommonResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.CommonRespDef.internal_static_CommonResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.CommonRespDef.CommonResp.class, org.gameprototype.proto.src.CommonRespDef.CommonResp.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.CommonRespDef.CommonResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.CommonRespDef.internal_static_CommonResp_descriptor;
      }

      public org.gameprototype.proto.src.CommonRespDef.CommonResp getDefaultInstanceForType() {
        return org.gameprototype.proto.src.CommonRespDef.CommonResp.getDefaultInstance();
      }

      public org.gameprototype.proto.src.CommonRespDef.CommonResp build() {
        org.gameprototype.proto.src.CommonRespDef.CommonResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.CommonRespDef.CommonResp buildPartial() {
        org.gameprototype.proto.src.CommonRespDef.CommonResp result = new org.gameprototype.proto.src.CommonRespDef.CommonResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.CommonRespDef.CommonResp) {
          return mergeFrom((org.gameprototype.proto.src.CommonRespDef.CommonResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.CommonRespDef.CommonResp other) {
        if (other == org.gameprototype.proto.src.CommonRespDef.CommonResp.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000002;
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.CommonRespDef.CommonResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.CommonRespDef.CommonResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode code_ = org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode.SUCCESS;
      /**
       * <code>required .CommonResp.RespCode code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CommonResp.RespCode code = 1;</code>
       */
      public org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode getCode() {
        return code_;
      }
      /**
       * <code>required .CommonResp.RespCode code = 1;</code>
       */
      public Builder setCode(org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .CommonResp.RespCode code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = org.gameprototype.proto.src.CommonRespDef.CommonResp.RespCode.SUCCESS;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 2;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string info = 2;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            info_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 2;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 2;</code>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 2;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        info_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CommonResp)
    }

    static {
      defaultInstance = new CommonResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CommonResp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommonResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CommonRespDef.proto\"\205\003\n\nCommonResp\022\"\n\004" +
      "code\030\001 \002(\0162\024.CommonResp.RespCode\022\014\n\004info" +
      "\030\002 \001(\t\"\304\002\n\010RespCode\022\013\n\007SUCCESS\020\000\022\032\n\025PARS" +
      "E_REQ_PARAM_ERROR\020\220\003\022\023\n\016INTERNAL_ERROR\020\364" +
      "\003\022\"\n\025LOGIN_ACCOUNT_UNEXIST\020\377\377\377\377\377\377\377\377\377\001\022!\n" +
      "\024LOGIN_PASSWORD_ERROR\020\376\377\377\377\377\377\377\377\377\001\022)\n\034LOGI" +
      "N_ACCOUNT_ALREADY_ONLINE\020\375\377\377\377\377\377\377\377\377\001\022,\n\037R" +
      "EGISTER_ACCOUNT_ALREADY_EXISTS\020\374\377\377\377\377\377\377\377\377" +
      "\001\022*\n\035REGISTER_ACCOUNT_NAME_ILLEGAL\020\373\377\377\377\377" +
      "\377\377\377\377\001\022.\n!REGISTER_ACCOUNT_PASSWORD_ILLEG",
      "AL\020\372\377\377\377\377\377\377\377\377\001B\035\n\033org.gameprototype.proto" +
      ".src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CommonResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CommonResp_descriptor,
        new java.lang.String[] { "Code", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
