// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerEquipDTODef.proto

package org.gameprototype.proto.src;

public final class PlayerEquipDTODef {
  private PlayerEquipDTODef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerEquipDTOPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerEquipDTOPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 playerEquipId = 1;</code>
     */
    boolean hasPlayerEquipId();
    /**
     * <code>required int64 playerEquipId = 1;</code>
     */
    long getPlayerEquipId();

    /**
     * <code>required int64 playerRoleId = 2;</code>
     */
    boolean hasPlayerRoleId();
    /**
     * <code>required int64 playerRoleId = 2;</code>
     */
    long getPlayerRoleId();

    /**
     * <code>required int64 equipId = 3;</code>
     */
    boolean hasEquipId();
    /**
     * <code>required int64 equipId = 3;</code>
     */
    long getEquipId();

    /**
     * <code>optional int64 status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int64 status = 4;</code>
     */
    long getStatus();
  }
  /**
   * Protobuf type {@code PlayerEquipDTOPB}
   */
  public static final class PlayerEquipDTOPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerEquipDTOPB)
      PlayerEquipDTOPBOrBuilder {
    // Use PlayerEquipDTOPB.newBuilder() to construct.
    private PlayerEquipDTOPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerEquipDTOPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerEquipDTOPB defaultInstance;
    public static PlayerEquipDTOPB getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerEquipDTOPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerEquipDTOPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerEquipId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              playerRoleId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              equipId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              status_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.PlayerEquipDTODef.internal_static_PlayerEquipDTOPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.PlayerEquipDTODef.internal_static_PlayerEquipDTOPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.class, org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerEquipDTOPB> PARSER =
        new com.google.protobuf.AbstractParser<PlayerEquipDTOPB>() {
      public PlayerEquipDTOPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerEquipDTOPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerEquipDTOPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYEREQUIPID_FIELD_NUMBER = 1;
    private long playerEquipId_;
    /**
     * <code>required int64 playerEquipId = 1;</code>
     */
    public boolean hasPlayerEquipId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 playerEquipId = 1;</code>
     */
    public long getPlayerEquipId() {
      return playerEquipId_;
    }

    public static final int PLAYERROLEID_FIELD_NUMBER = 2;
    private long playerRoleId_;
    /**
     * <code>required int64 playerRoleId = 2;</code>
     */
    public boolean hasPlayerRoleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 playerRoleId = 2;</code>
     */
    public long getPlayerRoleId() {
      return playerRoleId_;
    }

    public static final int EQUIPID_FIELD_NUMBER = 3;
    private long equipId_;
    /**
     * <code>required int64 equipId = 3;</code>
     */
    public boolean hasEquipId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 equipId = 3;</code>
     */
    public long getEquipId() {
      return equipId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private long status_;
    /**
     * <code>optional int64 status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 status = 4;</code>
     */
    public long getStatus() {
      return status_;
    }

    private void initFields() {
      playerEquipId_ = 0L;
      playerRoleId_ = 0L;
      equipId_ = 0L;
      status_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerEquipId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEquipId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerEquipId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, playerRoleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, equipId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerEquipId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerRoleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, equipId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerEquipDTOPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerEquipDTOPB)
        org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.PlayerEquipDTODef.internal_static_PlayerEquipDTOPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.PlayerEquipDTODef.internal_static_PlayerEquipDTOPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.class, org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerEquipId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerRoleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        equipId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.PlayerEquipDTODef.internal_static_PlayerEquipDTOPB_descriptor;
      }

      public org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB getDefaultInstanceForType() {
        return org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.getDefaultInstance();
      }

      public org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB build() {
        org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB buildPartial() {
        org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB result = new org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerEquipId_ = playerEquipId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerRoleId_ = playerRoleId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.equipId_ = equipId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB) {
          return mergeFrom((org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB other) {
        if (other == org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB.getDefaultInstance()) return this;
        if (other.hasPlayerEquipId()) {
          setPlayerEquipId(other.getPlayerEquipId());
        }
        if (other.hasPlayerRoleId()) {
          setPlayerRoleId(other.getPlayerRoleId());
        }
        if (other.hasEquipId()) {
          setEquipId(other.getEquipId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerEquipId()) {
          
          return false;
        }
        if (!hasPlayerRoleId()) {
          
          return false;
        }
        if (!hasEquipId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.PlayerEquipDTODef.PlayerEquipDTOPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerEquipId_ ;
      /**
       * <code>required int64 playerEquipId = 1;</code>
       */
      public boolean hasPlayerEquipId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 playerEquipId = 1;</code>
       */
      public long getPlayerEquipId() {
        return playerEquipId_;
      }
      /**
       * <code>required int64 playerEquipId = 1;</code>
       */
      public Builder setPlayerEquipId(long value) {
        bitField0_ |= 0x00000001;
        playerEquipId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerEquipId = 1;</code>
       */
      public Builder clearPlayerEquipId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerEquipId_ = 0L;
        onChanged();
        return this;
      }

      private long playerRoleId_ ;
      /**
       * <code>required int64 playerRoleId = 2;</code>
       */
      public boolean hasPlayerRoleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 playerRoleId = 2;</code>
       */
      public long getPlayerRoleId() {
        return playerRoleId_;
      }
      /**
       * <code>required int64 playerRoleId = 2;</code>
       */
      public Builder setPlayerRoleId(long value) {
        bitField0_ |= 0x00000002;
        playerRoleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerRoleId = 2;</code>
       */
      public Builder clearPlayerRoleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerRoleId_ = 0L;
        onChanged();
        return this;
      }

      private long equipId_ ;
      /**
       * <code>required int64 equipId = 3;</code>
       */
      public boolean hasEquipId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 equipId = 3;</code>
       */
      public long getEquipId() {
        return equipId_;
      }
      /**
       * <code>required int64 equipId = 3;</code>
       */
      public Builder setEquipId(long value) {
        bitField0_ |= 0x00000004;
        equipId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 equipId = 3;</code>
       */
      public Builder clearEquipId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        equipId_ = 0L;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>optional int64 status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 status = 4;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <code>optional int64 status = 4;</code>
       */
      public Builder setStatus(long value) {
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerEquipDTOPB)
    }

    static {
      defaultInstance = new PlayerEquipDTOPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerEquipDTOPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerEquipDTOPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerEquipDTOPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027PlayerEquipDTODef.proto\"`\n\020PlayerEquip" +
      "DTOPB\022\025\n\rplayerEquipId\030\001 \002(\003\022\024\n\014playerRo" +
      "leId\030\002 \002(\003\022\017\n\007equipId\030\003 \002(\003\022\016\n\006status\030\004 " +
      "\001(\003B\035\n\033org.gameprototype.proto.src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerEquipDTOPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerEquipDTOPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerEquipDTOPB_descriptor,
        new java.lang.String[] { "PlayerEquipId", "PlayerRoleId", "EquipId", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
