// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerRoleDTODef.proto

package org.gameprototype.proto.src;

public final class PlayerRoleDTODef {
  private PlayerRoleDTODef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerRoleDTOPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerRoleDTOPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 playerRoleId = 1;</code>
     */
    boolean hasPlayerRoleId();
    /**
     * <code>required int64 playerRoleId = 1;</code>
     */
    long getPlayerRoleId();
  }
  /**
   * Protobuf type {@code PlayerRoleDTOPB}
   */
  public static final class PlayerRoleDTOPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerRoleDTOPB)
      PlayerRoleDTOPBOrBuilder {
    // Use PlayerRoleDTOPB.newBuilder() to construct.
    private PlayerRoleDTOPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerRoleDTOPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerRoleDTOPB defaultInstance;
    public static PlayerRoleDTOPB getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerRoleDTOPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerRoleDTOPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerRoleId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.PlayerRoleDTODef.internal_static_PlayerRoleDTOPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.PlayerRoleDTODef.internal_static_PlayerRoleDTOPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.class, org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerRoleDTOPB> PARSER =
        new com.google.protobuf.AbstractParser<PlayerRoleDTOPB>() {
      public PlayerRoleDTOPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerRoleDTOPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRoleDTOPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYERROLEID_FIELD_NUMBER = 1;
    private long playerRoleId_;
    /**
     * <code>required int64 playerRoleId = 1;</code>
     */
    public boolean hasPlayerRoleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 playerRoleId = 1;</code>
     */
    public long getPlayerRoleId() {
      return playerRoleId_;
    }

    private void initFields() {
      playerRoleId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerRoleId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerRoleId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerRoleDTOPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerRoleDTOPB)
        org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.PlayerRoleDTODef.internal_static_PlayerRoleDTOPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.PlayerRoleDTODef.internal_static_PlayerRoleDTOPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.class, org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerRoleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.PlayerRoleDTODef.internal_static_PlayerRoleDTOPB_descriptor;
      }

      public org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB getDefaultInstanceForType() {
        return org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.getDefaultInstance();
      }

      public org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB build() {
        org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB buildPartial() {
        org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB result = new org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerRoleId_ = playerRoleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB) {
          return mergeFrom((org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB other) {
        if (other == org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB.getDefaultInstance()) return this;
        if (other.hasPlayerRoleId()) {
          setPlayerRoleId(other.getPlayerRoleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerRoleId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.PlayerRoleDTODef.PlayerRoleDTOPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerRoleId_ ;
      /**
       * <code>required int64 playerRoleId = 1;</code>
       */
      public boolean hasPlayerRoleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 playerRoleId = 1;</code>
       */
      public long getPlayerRoleId() {
        return playerRoleId_;
      }
      /**
       * <code>required int64 playerRoleId = 1;</code>
       */
      public Builder setPlayerRoleId(long value) {
        bitField0_ |= 0x00000001;
        playerRoleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerRoleId = 1;</code>
       */
      public Builder clearPlayerRoleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerRoleId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerRoleDTOPB)
    }

    static {
      defaultInstance = new PlayerRoleDTOPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerRoleDTOPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerRoleDTOPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerRoleDTOPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026PlayerRoleDTODef.proto\"\'\n\017PlayerRoleDT" +
      "OPB\022\024\n\014playerRoleId\030\001 \002(\003B\035\n\033org.gamepro" +
      "totype.proto.src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerRoleDTOPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerRoleDTOPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerRoleDTOPB_descriptor,
        new java.lang.String[] { "PlayerRoleId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
