// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerTeamDTODef.proto

package org.gameprototype.proto.src;

public final class PlayerTeamDTODef {
  private PlayerTeamDTODef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerTeamDTOPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerTeamDTOPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required int64 leaderId = 2;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required int64 leaderId = 2;</code>
     */
    long getLeaderId();

    /**
     * <code>required string memberId = 3;</code>
     */
    boolean hasMemberId();
    /**
     * <code>required string memberId = 3;</code>
     */
    java.lang.String getMemberId();
    /**
     * <code>required string memberId = 3;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();

    /**
     * <code>required string statuses = 4;</code>
     */
    boolean hasStatuses();
    /**
     * <code>required string statuses = 4;</code>
     */
    java.lang.String getStatuses();
    /**
     * <code>required string statuses = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusesBytes();
  }
  /**
   * Protobuf type {@code PlayerTeamDTOPB}
   */
  public static final class PlayerTeamDTOPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerTeamDTOPB)
      PlayerTeamDTOPBOrBuilder {
    // Use PlayerTeamDTOPB.newBuilder() to construct.
    private PlayerTeamDTOPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerTeamDTOPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerTeamDTOPB defaultInstance;
    public static PlayerTeamDTOPB getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerTeamDTOPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerTeamDTOPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leaderId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              memberId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              statuses_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.PlayerTeamDTODef.internal_static_PlayerTeamDTOPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.PlayerTeamDTODef.internal_static_PlayerTeamDTOPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.class, org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerTeamDTOPB> PARSER =
        new com.google.protobuf.AbstractParser<PlayerTeamDTOPB>() {
      public PlayerTeamDTOPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerTeamDTOPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerTeamDTOPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private long leaderId_;
    /**
     * <code>required int64 leaderId = 2;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 leaderId = 2;</code>
     */
    public long getLeaderId() {
      return leaderId_;
    }

    public static final int MEMBERID_FIELD_NUMBER = 3;
    private java.lang.Object memberId_;
    /**
     * <code>required string memberId = 3;</code>
     */
    public boolean hasMemberId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string memberId = 3;</code>
     */
    public java.lang.String getMemberId() {
      java.lang.Object ref = memberId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memberId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string memberId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      java.lang.Object ref = memberId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUSES_FIELD_NUMBER = 4;
    private java.lang.Object statuses_;
    /**
     * <code>required string statuses = 4;</code>
     */
    public boolean hasStatuses() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string statuses = 4;</code>
     */
    public java.lang.String getStatuses() {
      java.lang.Object ref = statuses_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statuses_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string statuses = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusesBytes() {
      java.lang.Object ref = statuses_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statuses_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      leaderId_ = 0L;
      memberId_ = "";
      statuses_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemberId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatuses()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMemberIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStatusesBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMemberIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStatusesBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerTeamDTOPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerTeamDTOPB)
        org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.PlayerTeamDTODef.internal_static_PlayerTeamDTOPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.PlayerTeamDTODef.internal_static_PlayerTeamDTOPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.class, org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        memberId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        statuses_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.PlayerTeamDTODef.internal_static_PlayerTeamDTOPB_descriptor;
      }

      public org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB getDefaultInstanceForType() {
        return org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.getDefaultInstance();
      }

      public org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB build() {
        org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB buildPartial() {
        org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB result = new org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.memberId_ = memberId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.statuses_ = statuses_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB) {
          return mergeFrom((org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB other) {
        if (other == org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasMemberId()) {
          bitField0_ |= 0x00000004;
          memberId_ = other.memberId_;
          onChanged();
        }
        if (other.hasStatuses()) {
          bitField0_ |= 0x00000008;
          statuses_ = other.statuses_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLeaderId()) {
          
          return false;
        }
        if (!hasMemberId()) {
          
          return false;
        }
        if (!hasStatuses()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.PlayerTeamDTODef.PlayerTeamDTOPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long leaderId_ ;
      /**
       * <code>required int64 leaderId = 2;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 leaderId = 2;</code>
       */
      public long getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>required int64 leaderId = 2;</code>
       */
      public Builder setLeaderId(long value) {
        bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 leaderId = 2;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object memberId_ = "";
      /**
       * <code>required string memberId = 3;</code>
       */
      public boolean hasMemberId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string memberId = 3;</code>
       */
      public java.lang.String getMemberId() {
        java.lang.Object ref = memberId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            memberId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string memberId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        java.lang.Object ref = memberId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memberId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string memberId = 3;</code>
       */
      public Builder setMemberId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string memberId = 3;</code>
       */
      public Builder clearMemberId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memberId_ = getDefaultInstance().getMemberId();
        onChanged();
        return this;
      }
      /**
       * <code>required string memberId = 3;</code>
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memberId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object statuses_ = "";
      /**
       * <code>required string statuses = 4;</code>
       */
      public boolean hasStatuses() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string statuses = 4;</code>
       */
      public java.lang.String getStatuses() {
        java.lang.Object ref = statuses_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            statuses_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string statuses = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusesBytes() {
        java.lang.Object ref = statuses_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statuses_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string statuses = 4;</code>
       */
      public Builder setStatuses(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        statuses_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string statuses = 4;</code>
       */
      public Builder clearStatuses() {
        bitField0_ = (bitField0_ & ~0x00000008);
        statuses_ = getDefaultInstance().getStatuses();
        onChanged();
        return this;
      }
      /**
       * <code>required string statuses = 4;</code>
       */
      public Builder setStatusesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        statuses_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerTeamDTOPB)
    }

    static {
      defaultInstance = new PlayerTeamDTOPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerTeamDTOPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerTeamDTOPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerTeamDTOPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026PlayerTeamDTODef.proto\"S\n\017PlayerTeamDT" +
      "OPB\022\n\n\002id\030\001 \002(\003\022\020\n\010leaderId\030\002 \002(\003\022\020\n\010mem" +
      "berId\030\003 \002(\t\022\020\n\010statuses\030\004 \002(\tB\035\n\033org.gam" +
      "eprototype.proto.src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PlayerTeamDTOPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerTeamDTOPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerTeamDTOPB_descriptor,
        new java.lang.String[] { "Id", "LeaderId", "MemberId", "Statuses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
