// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SocketModelDef.proto

package org.gameprototype.proto.src;

public final class SocketModelDef {
  private SocketModelDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SocketModelPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SocketModelPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>required int32 area = 2;</code>
     */
    boolean hasArea();
    /**
     * <code>required int32 area = 2;</code>
     */
    int getArea();

    /**
     * <code>required int32 command = 3;</code>
     */
    boolean hasCommand();
    /**
     * <code>required int32 command = 3;</code>
     */
    int getCommand();

    /**
     * <code>required bytes content = 4;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code SocketModelPB}
   */
  public static final class SocketModelPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SocketModelPB)
      SocketModelPBOrBuilder {
    // Use SocketModelPB.newBuilder() to construct.
    private SocketModelPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SocketModelPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SocketModelPB defaultInstance;
    public static SocketModelPB getDefaultInstance() {
      return defaultInstance;
    }

    public SocketModelPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SocketModelPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              area_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              command_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gameprototype.proto.src.SocketModelDef.internal_static_SocketModelPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gameprototype.proto.src.SocketModelDef.internal_static_SocketModelPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gameprototype.proto.src.SocketModelDef.SocketModelPB.class, org.gameprototype.proto.src.SocketModelDef.SocketModelPB.Builder.class);
    }

    public static com.google.protobuf.Parser<SocketModelPB> PARSER =
        new com.google.protobuf.AbstractParser<SocketModelPB>() {
      public SocketModelPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SocketModelPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SocketModelPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int AREA_FIELD_NUMBER = 2;
    private int area_;
    /**
     * <code>required int32 area = 2;</code>
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 area = 2;</code>
     */
    public int getArea() {
      return area_;
    }

    public static final int COMMAND_FIELD_NUMBER = 3;
    private int command_;
    /**
     * <code>required int32 command = 3;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 command = 3;</code>
     */
    public int getCommand() {
      return command_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes content = 4;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      type_ = 0;
      area_ = 0;
      command_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArea()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, area_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, command_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, area_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, command_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.gameprototype.proto.src.SocketModelDef.SocketModelPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.gameprototype.proto.src.SocketModelDef.SocketModelPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SocketModelPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SocketModelPB)
        org.gameprototype.proto.src.SocketModelDef.SocketModelPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gameprototype.proto.src.SocketModelDef.internal_static_SocketModelPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gameprototype.proto.src.SocketModelDef.internal_static_SocketModelPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gameprototype.proto.src.SocketModelDef.SocketModelPB.class, org.gameprototype.proto.src.SocketModelDef.SocketModelPB.Builder.class);
      }

      // Construct using org.gameprototype.proto.src.SocketModelDef.SocketModelPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        area_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gameprototype.proto.src.SocketModelDef.internal_static_SocketModelPB_descriptor;
      }

      public org.gameprototype.proto.src.SocketModelDef.SocketModelPB getDefaultInstanceForType() {
        return org.gameprototype.proto.src.SocketModelDef.SocketModelPB.getDefaultInstance();
      }

      public org.gameprototype.proto.src.SocketModelDef.SocketModelPB build() {
        org.gameprototype.proto.src.SocketModelDef.SocketModelPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.gameprototype.proto.src.SocketModelDef.SocketModelPB buildPartial() {
        org.gameprototype.proto.src.SocketModelDef.SocketModelPB result = new org.gameprototype.proto.src.SocketModelDef.SocketModelPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.area_ = area_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gameprototype.proto.src.SocketModelDef.SocketModelPB) {
          return mergeFrom((org.gameprototype.proto.src.SocketModelDef.SocketModelPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gameprototype.proto.src.SocketModelDef.SocketModelPB other) {
        if (other == org.gameprototype.proto.src.SocketModelDef.SocketModelPB.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasArea()) {
          setArea(other.getArea());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasArea()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gameprototype.proto.src.SocketModelDef.SocketModelPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gameprototype.proto.src.SocketModelDef.SocketModelPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int area_ ;
      /**
       * <code>required int32 area = 2;</code>
       */
      public boolean hasArea() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 area = 2;</code>
       */
      public int getArea() {
        return area_;
      }
      /**
       * <code>required int32 area = 2;</code>
       */
      public Builder setArea(int value) {
        bitField0_ |= 0x00000002;
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 area = 2;</code>
       */
      public Builder clearArea() {
        bitField0_ = (bitField0_ & ~0x00000002);
        area_ = 0;
        onChanged();
        return this;
      }

      private int command_ ;
      /**
       * <code>required int32 command = 3;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 command = 3;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <code>required int32 command = 3;</code>
       */
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000004;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 command = 3;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SocketModelPB)
    }

    static {
      defaultInstance = new SocketModelPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SocketModelPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SocketModelPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SocketModelPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SocketModelDef.proto\"M\n\rSocketModelPB\022" +
      "\014\n\004type\030\001 \002(\005\022\014\n\004area\030\002 \002(\005\022\017\n\007command\030\003" +
      " \002(\005\022\017\n\007content\030\004 \002(\014B\035\n\033org.gameprototy" +
      "pe.proto.src"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SocketModelPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SocketModelPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SocketModelPB_descriptor,
        new java.lang.String[] { "Type", "Area", "Command", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
