package org.gameprototype.dao.mapper;

import org.gameprototype.dao.model.PlayerTeam;

public interface PlayerTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    int insert(PlayerTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    int insertSelective(PlayerTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    PlayerTeam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    int updateByPrimaryKeySelective(PlayerTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_team
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    int updateByPrimaryKey(PlayerTeam record);
}