package org.gameprototype.dao.mapper;

import org.gameprototype.dao.model.PlayerModel;

import java.util.List;

public interface PlayerModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    int insert(PlayerModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    int insertSelective(PlayerModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    PlayerModel selectByPrimaryKey(Integer id);

    List<PlayerModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    int updateByPrimaryKeySelective(PlayerModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_model
     *
     * @mbggenerated Wed Sep 16 12:05:17 CST 2015
     */
    int updateByPrimaryKey(PlayerModel record);
}