package org.gameprototype.dao.mapper;

import org.gameprototype.dao.model.PlayerEquip;

import java.util.List;

public interface PlayerEquipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByPlayerEquip(PlayerEquip equip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    int insert(PlayerEquip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    int insertSelective(PlayerEquip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    PlayerEquip selectByPrimaryKey(Integer id);

    List<PlayerEquip> selectByPlayerId(Integer playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    int updateByPrimaryKeySelective(PlayerEquip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_equip
     *
     * @mbggenerated Wed Sep 16 15:06:45 CST 2015
     */
    int updateByPrimaryKey(PlayerEquip record);
}