package org.gameprototype.dao.mapper;

import java.util.List;

import org.gameprototype.dao.model.Shop;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    Shop selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    int updateByPrimaryKey(Shop record);
    
    /**
     * 根据类型获取列表
     * This method corresponds to the database table shop
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    List<Shop> getItemList(int itemType,int offset);
}