package org.gameprototype.dao.model;

public class GameMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.id
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.name
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.hitpoints
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private Integer hitpoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.damage
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private Integer damage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.defense
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private Integer defense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamemap.level
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.id
     *
     * @return the value of gamemap.id
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.id
     *
     * @param id the value for gamemap.id
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.name
     *
     * @return the value of gamemap.name
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.name
     *
     * @param name the value for gamemap.name
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.hitpoints
     *
     * @return the value of gamemap.hitpoints
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public Integer getHitpoints() {
        return hitpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.hitpoints
     *
     * @param hitpoints the value for gamemap.hitpoints
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setHitpoints(Integer hitpoints) {
        this.hitpoints = hitpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.damage
     *
     * @return the value of gamemap.damage
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public Integer getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.damage
     *
     * @param damage the value for gamemap.damage
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setDamage(Integer damage) {
        this.damage = damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.defense
     *
     * @return the value of gamemap.defense
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public Integer getDefense() {
        return defense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.defense
     *
     * @param defense the value for gamemap.defense
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setDefense(Integer defense) {
        this.defense = defense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamemap.level
     *
     * @return the value of gamemap.level
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamemap.level
     *
     * @param level the value for gamemap.level
     *
     * @mbggenerated Tue Oct 20 15:20:49 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}