package org.gameprototype.dao.model;

import java.awt.*;
import java.io.Serializable;
import java.util.Date;

public class PlayerRole implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.name
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.desc
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer hitpoints;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.damage
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer damage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.defense
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer defense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.level
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.account_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.status
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.current_hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer currentHitpoints;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.experience
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer experience;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.model_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer modelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.equip_max
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Integer equipMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.create_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player_role.modify_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.id
	 * @return  the value of player_role.id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.id
	 * @param id  the value for player_role.id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.name
	 * @return  the value of player_role.name
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.name
	 * @param name  the value for player_role.name
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.desc
	 * @return  the value of player_role.desc
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.desc
	 * @param desc  the value for player_role.desc
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.hitpoints
	 * @return  the value of player_role.hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getHitpoints() {
		return hitpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.hitpoints
	 * @param hitpoints  the value for player_role.hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setHitpoints(Integer hitpoints) {
		this.hitpoints = hitpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.damage
	 * @return  the value of player_role.damage
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getDamage() {
		return damage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.damage
	 * @param damage  the value for player_role.damage
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setDamage(Integer damage) {
		this.damage = damage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.defense
	 * @return  the value of player_role.defense
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getDefense() {
		return defense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.defense
	 * @param defense  the value for player_role.defense
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setDefense(Integer defense) {
		this.defense = defense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.level
	 * @return  the value of player_role.level
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.level
	 * @param level  the value for player_role.level
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.account_id
	 * @return  the value of player_role.account_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.account_id
	 * @param accountId  the value for player_role.account_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.status
	 * @return  the value of player_role.status
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.status
	 * @param status  the value for player_role.status
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.current_hitpoints
	 * @return  the value of player_role.current_hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getCurrentHitpoints() {
		return currentHitpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.current_hitpoints
	 * @param currentHitpoints  the value for player_role.current_hitpoints
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setCurrentHitpoints(Integer currentHitpoints) {
		this.currentHitpoints = currentHitpoints;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.experience
	 * @return  the value of player_role.experience
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getExperience() {
		return experience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.experience
	 * @param experience  the value for player_role.experience
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.model_id
	 * @return  the value of player_role.model_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getModelId() {
		return modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.model_id
	 * @param modelId  the value for player_role.model_id
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.equip_max
	 * @return  the value of player_role.equip_max
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Integer getEquipMax() {
		return equipMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.equip_max
	 * @param equipMax  the value for player_role.equip_max
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setEquipMax(Integer equipMax) {
		this.equipMax = equipMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.create_time
	 * @return  the value of player_role.create_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.create_time
	 * @param createTime  the value for player_role.create_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player_role.modify_time
	 * @return  the value of player_role.modify_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player_role.modify_time
	 * @param modifyTime  the value for player_role.modify_time
	 * @mbggenerated  Thu Sep 24 11:31:20 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
     * 玩家坐标
     */
    private Point coordinate;

    public Point getCoordinate() {
        return coordinate;
    }

    public void setCoordinate(Point coordinate) {
        this.coordinate = coordinate;
    }
}