package org.gameprototype.dao.model;

import java.io.Serializable;

public class PlayerTeam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.leader_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private Integer leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.member_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.status
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.gmt_create
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private Integer gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_team.gmt_update
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    private Integer gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.id
     *
     * @return the value of player_team.id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.id
     *
     * @param id the value for player_team.id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.leader_id
     *
     * @return the value of player_team.leader_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public Integer getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.leader_id
     *
     * @param leaderId the value for player_team.leader_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.member_id
     *
     * @return the value of player_team.member_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.member_id
     *
     * @param memberId the value for player_team.member_id
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.status
     *
     * @return the value of player_team.status
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.status
     *
     * @param status the value for player_team.status
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.gmt_create
     *
     * @return the value of player_team.gmt_create
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public Integer getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.gmt_create
     *
     * @param gmtCreate the value for player_team.gmt_create
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_team.gmt_update
     *
     * @return the value of player_team.gmt_update
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public Integer getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_team.gmt_update
     *
     * @param gmtUpdate the value for player_team.gmt_update
     *
     * @mbggenerated Mon Sep 21 10:28:44 CST 2015
     */
    public void setGmtUpdate(Integer gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}