package org.gameprototype.dao.model;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_id
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_type
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Integer itemType;  

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_name
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_buyprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Integer itemBuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_sellprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Integer itemSellprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_value
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Integer itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.is_delete
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.description
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.item_url
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    private String itemUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_id
     *
     * @return the value of shop.item_id
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_id
     *
     * @param itemId the value for shop.item_id
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_type
     *
     * @return the value of shop.item_type
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_type
     *
     * @param itemType the value for shop.item_type
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_name
     *
     * @return the value of shop.item_name
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_name
     *
     * @param itemName the value for shop.item_name
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_buyprice
     *
     * @return the value of shop.item_buyprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Integer getItemBuyprice() {
        return itemBuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_buyprice
     *
     * @param itemBuyprice the value for shop.item_buyprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemBuyprice(Integer itemBuyprice) {
        this.itemBuyprice = itemBuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_sellprice
     *
     * @return the value of shop.item_sellprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Integer getItemSellprice() {
        return itemSellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_sellprice
     *
     * @param itemSellprice the value for shop.item_sellprice
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemSellprice(Integer itemSellprice) {
        this.itemSellprice = itemSellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_value
     *
     * @return the value of shop.item_value
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Integer getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_value
     *
     * @param itemValue the value for shop.item_value
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemValue(Integer itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.is_delete
     *
     * @return the value of shop.is_delete
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.is_delete
     *
     * @param isDelete the value for shop.is_delete
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.description
     *
     * @return the value of shop.description
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.description
     *
     * @param description the value for shop.description
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.item_url
     *
     * @return the value of shop.item_url
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public String getItemUrl() {
        return itemUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.item_url
     *
     * @param itemUrl the value for shop.item_url
     *
     * @mbggenerated Tue Sep 15 11:30:55 CST 2015
     */
    public void setItemUrl(String itemUrl) {
        this.itemUrl = itemUrl;
    }
}